### ISSUE TITLE
Screenshots don't actually appear in your website

### ISSUE THREAD

**Issue by KSXGitHub** [nlogozzo/nlogozzo.github.io#1]
![nickvision](https://user-images.githubusercontent.com/11488886/229542592-9eadd7d2-cdce-46b2-abfc-a1cbede26939.png)

**Comment by nlogozzo** [comment]
Hmmm it shows in the readme file correctly...let me try to figure it out

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/nlogozzo.github.io/commit/c2566743dfe21cd8ba3a51835cf58a24d4c3eae4
